# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Auto Fix Lockfile

on:
  workflow_dispatch:
  schedule:
    - cron: "27 3 * * *"

jobs:
  auto-fix-lockfile:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: üì∏ Snapshot Workflow Context
        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
        run: echo "$CONTEXT_GITHUB"

      - name: ‚úà Checkout default branch
        if: github.event_name != 'issue_comment'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: üì¶ Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "24"

      - name: ‚òï Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: "25"
          distribution: "corretto"

      - name: üêò Setup Gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: üîß Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: üîß Show Gradle version
        run: ./gradlew --version

      - name: üîß Check build-logic if exist
        id: check_build_logic
        continue-on-error: true
        run: ./gradlew :build-logic:help

      - name: üîè Write build-logic locks (conditional)
        if: steps.check_build_logic.outcome == 'success'
        run: ./gradlew :build-logic:writeLocks --no-parallel --no-configuration-cache

      - name: üîí Write global locks
        run: ./gradlew writeLocks --no-parallel --no-configuration-cache

      - name: üíæ Commit file changes (auto)
        id: auto-pr-lockfile
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "auto-pr/fix-lockfile"
          commit-message: "chore: auto fix lockfile [skip ci].."
          title: "chore: auto fix lockfile [skip ci].."
          labels: |
            pr|chore
          body: |
            ## Summary

            This PR fixes the lockfile.

      - name: üîß Show PR info
        env:
          PR_INFO: ${{ toJSON(steps.auto-pr-lockfile.outputs) }}
        run: |
          echo "PR info: $PR_INFO"

      - name: ‚è∏ Pause for VSCode Debug
        env:
          ACTION_DEBUG_TOKEN: ${{ secrets.ACTION_DEBUG_TOKEN }}
          CONTEXT_GITHUB: ${{ toJSON(github) }}
          CONTEXT_JOB: ${{ toJSON(job) }}
          CONTEXT_STEPS: ${{ toJSON(steps) }}
          CONTEXT_RUNNER: ${{ toJSON(runner) }}
          CONTEXT_MATRIX: ${{ toJSON(matrix) }}
          CONTEXT_NEEDS: ${{ toJSON(needs) }}
          CONTEXT_INPUTS: ${{ toJSON(inputs) }}
        if: env.ACTION_DEBUG_TOKEN != '' && (failure() || vars.ACTION_DEBUG_WORKFLOW == github.workflow)
        uses: fawazahmed0/action-debug-vscode@b86399d1033aab18cf8f962fc7f634f39c9945ec # v3
        with:
          token: ${{ env.ACTION_DEBUG_TOKEN }}
