# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# add this workflow to a repo to fix lock files for Renovate PRs
name: Fix Renovate

on:
  issue_comment:
    types: [created, edited]

jobs:
  lock-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: >-
      startsWith(github.event.comment.body, '/fix-lock') &&
      github.event.issue.pull_request != null &&
      (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR'
      )

    env:
      PR: ${{ github.event.issue.pull_request.html_url }}

    steps:
      - name: üì∏ Snapshot Workflow Context
        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
        run: echo "$CONTEXT_GITHUB"

      - name: üì° Get PR Data
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request != null
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        id: get-pr-data
        with:
          # language=javascript
          script: |
            console.log(`Get PR info: ${context.repo.owner}/${context.repo.repo}#${context.issue.number}`)
            const {data: pr} = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            console.log(`PR info: ${JSON.stringify(pr)}`)
            const prInfo = {
              num: context.issue.number,
              branchName: pr.head.ref,
              commit: pr.head.sha,
              committer: pr.head.user.login,
              repo: pr.head.repo.full_name
            }
            if (prInfo.committer === 'github-actions[bot]' || prInfo.committer === 'dependabot[bot]' || prInfo.committer === 'renovate[bot]') {
              console.log(`PR is from ${prInfo.committer}`)
            } else {
              console.log(`PR is not from ${prInfo.committer}`)
              core.setFailed(`PR is from ${prInfo.committer} is not allowed`)
            }
            core.setOutput('head_repo', prInfo.repo)
            core.setOutput('head_branch', prInfo.branchName)
            core.setOutput('committer', prInfo.committer)

      - name: üì° Use PR Branch
        run: |
          echo "The PR branch is ${{ steps.get-pr-data.outputs.head_branch }}"
          echo "The repository is ${{ steps.get-pr-data.outputs.head_repo }}"

      - name: ‚úà Checkout PR branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          repository: ${{ steps.get-pr-data.outputs.head_repo }}
          ref: ${{ steps.get-pr-data.outputs.head_branch }}

      - name: üì¶ Setup Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: "24"

      - name: ‚òï Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: "25"
          distribution: "corretto"

      - name: üêò Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: üîß Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: üîß Show Gradle version
        run: ./gradlew --version

      - name: üîè Write locks (only for bots)
        run: ./gradlew :build-logic:writeLocks writeLocks --no-parallel --no-configuration-cache

      - name: üìù Get Commit Message
        run: |
          COMMIT_MSG=$(git log --format=%s -n 1)
          echo "COMMIT_MSG=${COMMIT_MSG}" >> $GITHUB_ENV

      - name: üíæ Commit file changes (only for bots)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A

          git diff --cached --quiet || git commit -m "${COMMIT_MSG}"
          git push

      - name: üí¨ Add reaction to PR
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: hooray

      - name: ‚è∏ Pause for VSCode Debug
        env:
          ACTION_DEBUG_TOKEN: ${{ secrets.ACTION_DEBUG_TOKEN }}
          CONTEXT_GITHUB: ${{ toJSON(github) }}
          CONTEXT_JOB: ${{ toJSON(job) }}
          CONTEXT_STEPS: ${{ toJSON(steps) }}
          CONTEXT_RUNNER: ${{ toJSON(runner) }}
          CONTEXT_MATRIX: ${{ toJSON(matrix) }}
          CONTEXT_NEEDS: ${{ toJSON(needs) }}
          CONTEXT_INPUTS: ${{ toJSON(inputs) }}
        if: env.ACTION_DEBUG_TOKEN != '' && (failure() || vars.ACTION_DEBUG_WORKFLOW == github.workflow)
        uses: fawazahmed0/action-debug-vscode@b86399d1033aab18cf8f962fc7f634f39c9945ec # v3
        with:
          token: ${{ env.ACTION_DEBUG_TOKEN }}
