# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sync to Gitee

on:
  schedule:
    - cron: "16 0 * * *"
  workflow_dispatch:

jobs:
  sync-gitee:
    runs-on: ubuntu-latest

    steps:
      - name: â†ª Sync to Gitee
        uses: wearerequired/git-mirror-action@c44c68aebe42de49a80a8dfd557416b6a0cafdad # v1.2.0
        with:
          source-repo: "git@github.com:mymx2/starter-gradle.git"
          destination-repo: "git@gitee.com:mymx2/starter-gradle.git"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}

  action-debug:
    if: failure() || vars.ACTION_DEBUG_WORKFLOW == github.workflow
    uses: ./.github/workflows/_debug.yml
    secrets: inherit
