# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# https://docs.github.com/en/actions/reference/workflows-and-actions/reusing-workflow-configurations#supported-keywords-for-jobs-that-call-a-reusable-workflow
name: Publish Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  publish-release:
    if: >-
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/v') &&
      github.actor == 'mymx2'
    uses: ./.github/workflows/_publish.yml
    with:
      release: true
      changelog: true
    secrets: inherit

  action-debug:
    if: failure() || vars.ACTION_DEBUG_WORKFLOW == github.workflow
    uses: ./.github/workflows/_debug.yml
    secrets: inherit
