# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR Checks

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
  pull_request:
    branches:
      - main
      - minor
      - fix/**
      - feat/**
      - patch/**
  workflow_dispatch:

concurrency:
  # see: https://stackoverflow.com/a/72408109/30654190
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: âœˆ Checkout default branch
        if: github.event_name != 'issue_comment'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      - name: âœ Validate commit messages
        if: github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]'
        run: |
          chmod +x .github/workflows/shell/check-commit-msg.sh
          .github/workflows/shell/check-commit-msg.sh

      #      - name: ğŸ”€ Merge target branch into PR branch
      #        if: github.event_name == 'pull_request' || github.event_name == 'issue_comment'
      #        run: |
      #          git fetch origin ${{ github.base_ref }}:target-branch
      #          git merge --no-ff target-branch

      - name: ğŸ“¦ Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
        with:
          node-version: "24"

      - name: â˜• Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          java-version: "25"
          distribution: "corretto"

      - name: ğŸ˜ Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: ğŸ”§ Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: ğŸ”§ Show Gradle version
        run: ./gradlew --version

      #      - name: ğŸ¦† Run Actionlint
      #        run: ./gradlew runActionlint

      - name: ğŸ”’ Check locks
        if: github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]'
        run: ./gradlew :build-logic:checkLocks checkLocks

      - name: âœ… Run build checks
        run: ./gradlew :build-logic:check

      - name: ğŸ— Run main checks
        run: ./gradlew check

      - name: ğŸ§ª End-to-End tests
        run: ./gradlew testEndToEnd

      - name: ğŸ¢ Slow end-to-end tests
        run: ./gradlew testEndToEndSlow

      - name: ğŸ›  Generate CycloneDX BOM
        run: ./gradlew cyclonedxBom --no-configuration-cache

      - name: ğŸ“ˆ Generate Code Coverage Report
        run: ./gradlew testCodeCoverageReport

      - name: ğŸ“¤ Upload coverage to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          fail_ci_if_error: true
          verbose: true
          files: ./gradle/aggregation/build/reports/coverage/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: â¸ Pause for VSCode Debug
        env:
          ACTION_DEBUG_TOKEN: ${{ secrets.ACTION_DEBUG_TOKEN }}
          CONTEXT_GITHUB: ${{ toJSON(github) }}
          CONTEXT_JOB: ${{ toJSON(job) }}
          CONTEXT_STEPS: ${{ toJSON(steps) }}
          CONTEXT_RUNNER: ${{ toJSON(runner) }}
          CONTEXT_MATRIX: ${{ toJSON(matrix) }}
          CONTEXT_NEEDS: ${{ toJSON(needs) }}
          CONTEXT_INPUTS: ${{ toJSON(inputs) }}
        if: env.ACTION_DEBUG_TOKEN != '' && (failure() || vars.ACTION_DEBUG_WORKFLOW == github.workflow)
        uses: fawazahmed0/action-debug-vscode@b86399d1033aab18cf8f962fc7f634f39c9945ec
        with:
          token: ${{ env.ACTION_DEBUG_TOKEN }}
