# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR Checks

on:
  issue_comment:
    types: [created, edited]
  push:
    branches:
      - "**"
    tags:
      - "!**"
  pull_request:
    branches:
      - main
      - minor
      - fix/**
      - feat/**
      - patch/**
  workflow_dispatch:

concurrency:
  # see: https://stackoverflow.com/a/72408109/30654190
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      fast_run: ${{ github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/pr-check --fast') && github.event.comment.author_association != 'NONE' }}
    if: >-
      github.event_name != 'issue_comment' ||
      (
        startsWith(github.event.comment.body, '/pr-check') &&
        github.event.issue.pull_request != null &&
        (
          github.event.comment.author_association == 'OWNER' ||
          github.event.comment.author_association == 'MEMBER' ||
          github.event.comment.author_association == 'COLLABORATOR'
        )
      )

    steps:
      - name: üì° Get PR Data
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request != null
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        id: get-pr-data
        with:
          script: |
            console.log(`Get PR info: ${context.repo.owner}/${context.repo.repo}#${context.issue.number}`)
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            console.log(`PR info: ${JSON.stringify(pr)}`)
            return {
              num: context.issue.number,
              branchName: pr.head.ref,
              commit: pr.head.sha,
              committer: pr.head.user.login,
              repo: pr.head.repo.full_name
            }

      - name: üì° Use PR Branch
        run: |
          echo "The PR branch is ${{ steps.get-pr-data.outputs.result.repo }}"
          echo "The repository is ${{ steps.get-pr-data.outputs.result.branchName }}"

      - name: ‚úà Checkout PR branch
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request != null
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          repository: ${{ steps.get-pr-data.outputs.result.repo }}
          ref: ${{ steps.get-pr-data.outputs.result.branchName }}

      - name: ‚úà Checkout default branch
        if: github.event_name != 'issue_comment'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: ‚úè Validate commit messages
        if: github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]'
        run: |
          chmod +x .github/workflows/shell/check-commit-msg.sh
          .github/workflows/shell/check-commit-msg.sh

      #      - name: üîÄ Merge target branch into PR branch
      #        if: github.event_name == 'pull_request' || github.event_name == 'issue_comment'
      #        run: |
      #          git fetch origin ${{ github.base_ref }}:target-branch
      #          git merge --no-ff target-branch

      - name: üì¶ Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: "24"

      - name: ‚òï Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: "25"
          distribution: "corretto"

      - name: üêò Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: üîß Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: üîß Show Gradle version
        run: ./gradlew --version

      #      - name: ü¶Ü Run Actionlint
      #        run: ./gradlew runActionlint

      - name: üîí Check locks
        if: env.fast_run != 'true' && github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]'
        run: ./gradlew :build-logic:checkLocks checkLocks

      - name: ‚úÖ Run build checks
        run: ./gradlew :build-logic:check

      - name: üèó Run main checks
        run: ./gradlew check

      - name: üß™ End-to-End tests
        run: ./gradlew testEndToEnd

      - name: üê¢ Slow end-to-end tests
        if: env.fast_run != 'true'
        run: ./gradlew testEndToEndSlow

      - name: üõ† Generate CycloneDX BOM
        if: env.fast_run != 'true'
        run: ./gradlew cyclonedxBom --no-configuration-cache

      - name: üìà Generate Code Coverage Report
        if: env.fast_run != 'true'
        run: ./gradlew testCodeCoverageReport

      - name: üì§ Upload coverage to Codecov
        if: env.fast_run != 'true'
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          fail_ci_if_error: true
          verbose: true
          files: ./gradle/aggregation/build/reports/coverage/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: ‚è∏ Pause for VSCode Debug
        env:
          ACTION_DEBUG_TOKEN: ${{ secrets.ACTION_DEBUG_TOKEN }}
          CONTEXT_GITHUB: ${{ toJSON(github) }}
          CONTEXT_JOB: ${{ toJSON(job) }}
          CONTEXT_STEPS: ${{ toJSON(steps) }}
          CONTEXT_RUNNER: ${{ toJSON(runner) }}
          CONTEXT_MATRIX: ${{ toJSON(matrix) }}
          CONTEXT_NEEDS: ${{ toJSON(needs) }}
          CONTEXT_INPUTS: ${{ toJSON(inputs) }}
        if: env.ACTION_DEBUG_TOKEN != '' && (failure() || vars.ACTION_DEBUG_WORKFLOW == github.workflow)
        uses: fawazahmed0/action-debug-vscode@b86399d1033aab18cf8f962fc7f634f39c9945ec
        with:
          token: ${{ env.ACTION_DEBUG_TOKEN }}
