# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR Checks GitHub App

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
    paths:
      - ".github/actions/**"
  pull_request:
    branches:
      - main
      - minor
      - fix/**
      - feat/**
      - patch/**
    paths:
      - ".github/actions/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

env:
  APP_DIR: .github/actions

jobs:
  pr-checks-github-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/actions

    steps:
      - name: ‚úà Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: üì¶ Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: "24"

      - name: üèó Run main checks
        run: |
          npm i -g pnpm
          pnpm i
          pnpm lint

  action-debug:
    if: failure() || vars.ACTION_DEBUG_WORKFLOW == github.workflow
    uses: ./.github/workflows/_debug.yml
    secrets: inherit
