#file: noinspection UndefinedParamsPresent,UndefinedAction
name: PR Checks

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "!**"
  pull_request:
    branches:
      - main
      - minor

env:
  CI: true

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
      - name: âœˆ Checkout sources
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: ğŸ§© Validate commit messages
        if: github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]'
        run: |
          chmod +x .github/check-commit-msg.sh
          .github/check-commit-msg.sh

      - name: ğŸ“¦ Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: â˜• Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "corretto"

      - name: ğŸ˜ Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: ğŸ”§ Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: ğŸ”§ Show Gradle version
        run: ./gradlew --version

      - name: ğŸ”’ Check locks
        if: github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]'
        run: ./gradlew :build-logic:checkLocks checkLocks

      - name: ğŸ” Write locks (for bots)
        if: github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]'
        run: ./gradlew :build-logic:writeLocks writeLocks

      - run: ./gradlew :build-logic:check
      - run: ./gradlew check
      - run: ./gradlew testEndToEnd
      - run: ./gradlew testEndToEndSlow
      - run: ./gradlew cyclonedxBom --no-configuration-cache

      - name: ğŸ“Š Generate Code Coverage Report
        run: ./gradlew testCodeCoverageReport

      - name: ğŸ‘» Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          verbose: true
          files: ./gradle/aggregation/build/reports/coverage/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
