# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR Checks

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
  pull_request:
    branches:
      - main
      - minor
      - fix/**
      - feat/**
      - patch/**
  workflow_dispatch:

concurrency:
  # see: https://stackoverflow.com/a/72408109/30654190
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: üì∏ Snapshot Workflow Context
        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
        run: echo "$CONTEXT_GITHUB"

      - name: ‚úà Checkout default branch
        if: github.event_name != 'issue_comment'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: ‚úè Validate commit messages
        if: >
          github.event.pull_request.user.login != 'github-actions[bot]' &&
          github.event.pull_request.user.login != 'dependabot[bot]' &&
          github.event.pull_request.user.login != 'renovate[bot]'
        run: |
          chmod +x .github/workflows/shell/check-commit-msg.sh
          .github/workflows/shell/check-commit-msg.sh

      #      - name: üîÄ Merge target branch into PR branch
      #        if: github.event_name == 'pull_request' || github.event_name == 'issue_comment'
      #        run: |
      #          git fetch origin ${{ github.base_ref }}:target-branch
      #          git merge --no-ff target-branch

      - name: üì¶ Setup Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: "24"

      - name: ‚òï Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: "25"
          distribution: "corretto"

      - name: üêò Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: üîß Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: üîß Show Gradle version
        run: ./gradlew --version

      #      - name: ü¶Ü Run Actionlint
      #        run: ./gradlew runActionlint

      #      - name: üîí Check locks
      #        if: >
      #          github.event.pull_request.user.login != 'github-actions[bot]' &&
      #          github.event.pull_request.user.login != 'dependabot[bot]' &&
      #          github.event.pull_request.user.login != 'renovate[bot]'
      #        run: ./gradlew checkLocks --no-parallel

      - name: üèó Run main checks
        run: ./gradlew check

      - name: üõ† Generate CycloneDX BOM
        if: github.event_name != 'pull_request'
        run: ./gradlew cyclonedxBom --no-configuration-cache

      - name: üìà Generate Code Coverage Report
        if: github.event_name != 'pull_request'
        run: ./gradlew testCodeCoverageReport

      - name: üì§ Upload coverage to Codecov
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          fail_ci_if_error: true
          verbose: true
          files: ./gradle/aggregation/build/reports/coverage/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: ‚è∏ Pause for VSCode Debug
        env:
          ACTION_DEBUG_TOKEN: ${{ secrets.ACTION_DEBUG_TOKEN }}
          CONTEXT_GITHUB: ${{ toJSON(github) }}
          CONTEXT_JOB: ${{ toJSON(job) }}
          CONTEXT_STEPS: ${{ toJSON(steps) }}
          CONTEXT_RUNNER: ${{ toJSON(runner) }}
          CONTEXT_MATRIX: ${{ toJSON(matrix) }}
          CONTEXT_NEEDS: ${{ toJSON(needs) }}
          CONTEXT_INPUTS: ${{ toJSON(inputs) }}
        if: env.ACTION_DEBUG_TOKEN != '' && (failure() || vars.ACTION_DEBUG_WORKFLOW == github.workflow)
        uses: fawazahmed0/action-debug-vscode@b86399d1033aab18cf8f962fc7f634f39c9945ec # v3
        with:
          token: ${{ env.ACTION_DEBUG_TOKEN }}
